
services:
  postgres:
    image: postgres:16
    container_name: pg_estudos
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-minhaapi_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - pgdata_estudos:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-minhaapi_db}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.name: "PostgreSQL - Estudos"

  redis:
    image: redis:7-alpine
    container_name: redis_estudos
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.name: "Redis - Estudos"

volumes:
  pgdata_estudos:
    driver: local
  redis_data:
    driver: local
